
export const TRANSLATIONS = {
    ko: {
        badge: 'AI 퍼스널 컬러 진단',
        title: '나와 닮은 K-POP 아이돌은?',
        subtitle: '사진 한 장으로 퍼스널 컬러 진단과 닮은꼴 아이돌을 찾아보세요',
        uploadIcon: '📸',
        uploadText: '<span>사진을 업로드</span>하거나 여기에 끌어놓으세요',
        uploadHint: 'JPG, PNG (최대 10MB)',
        male: '👨 남자 아이돌',
        female: '👩 여자 아이돌',
        analyzeBtn: '✨ AI 분석 시작하기',
        loadingText: 'AI가 얼굴을 분석하고 있어요...',
        resultTitle: '퍼스널 컬러 진단 결과',
        resultSubtitle: 'AI가 분석한 당신의 스타일 리포트',
        bestColors: '베스트 컬러',
        avoidColors: '피해야 할 컬러',
        idolTitle: '닮은꼴 K-POP 아이돌 TOP 3',
        featureFace: '얼굴형',
        featureEye: '눈 모양',
        featureNose: '코 모양',
        featureLip: '입술 모양',
        featureVibe: '전체 분위기',
        ctaBtnText: '내 얼굴, 이 아이돌처럼 되려면?',
        ctaBtnSub: 'AI 성형상담소에서 눈코 상담 받기 →',
        shareTwitter: '𝕏 트위터 공유',
        saveImage: '📷 결과 저장하기',
        copyLink: '🔗 링크 복사',
        copied: '✅ 복사됨!',
        tweetText: '나랑 닮은 K-POP 아이돌은 {idol}! 당신의 퍼스널 컬러와 닮은꼴 아이돌을 확인해보세요 ✨ #KPOP #아이돌닮은꼴 #퍼스널컬러 https://kpop-idol-ai.vercel.app/',
        linkCopied: '✅ 링크가 복사되었습니다!',
        columnTitle: 'K-Beauty 스타일링 가이드',
        footerText: '© 2026 K-POP Idol AI. All rights reserved.',
        errorMsg: '분석 중 오류가 발생했습니다. 다시 시도해주세요.',
        noImage: '사진을 먼저 업로드해주세요.',
        retryBtn: '다시 분석하기',
        optimizingText: '🔄 이미지 최적화 중...',
        insightsTitle: '🎤 K-POP Insights',
        insightsSubtitle: 'K-POP의 역사와 글로벌 성공 비결을 알아보세요',
    },
    en: {
        badge: 'AI Personal Color Diagnosis',
        title: 'Which K-POP Idol Do You Look Like?',
        subtitle: 'Discover your personal color and K-POP idol lookalike with just one photo',
        uploadIcon: '📸',
        uploadText: '<span>Upload a photo</span> or drag and drop here',
        uploadHint: 'JPG, PNG (max 10MB)',
        male: '👨 Male Idol',
        female: '👩 Female Idol',
        analyzeBtn: '✨ Start AI Analysis',
        loadingText: 'AI is analyzing your face...',
        resultTitle: 'Personal Color Diagnosis Result',
        resultSubtitle: 'Your AI-powered style report',
        bestColors: 'Best Colors',
        avoidColors: 'Colors to Avoid',
        idolTitle: 'Top 3 Lookalike K-POP Idols',
        featureFace: 'Face Shape',
        featureEye: 'Eye Shape',
        featureNose: 'Nose Shape',
        featureLip: 'Lip Shape',
        featureVibe: 'Overall Vibe',
        ctaBtnText: 'Want to look like this idol?',
        ctaBtnSub: 'Get a free AI consultation at Beauty AI →',
        shareTwitter: '𝕏 Share on X',
        saveImage: '📷 Save Result',
        copyLink: '🔗 Copy Link',
        copied: '✅ Copied!',
        tweetText: 'My K-POP idol lookalike is {idol}! Find your personal color and idol match ✨ #KPOP #IdolLookalike #PersonalColor https://kpop-idol-ai.vercel.app/',
        linkCopied: '✅ Link copied!',
        columnTitle: 'K-Beauty Styling Guide',
        footerText: '© 2026 K-POP Idol AI. All rights reserved.',
        errorMsg: 'An error occurred during analysis. Please try again.',
        noImage: 'Please upload a photo first.',
        retryBtn: 'Analyze Again',
        optimizingText: '🔄 Optimizing image...',
        insightsTitle: '🎤 K-POP Insights',
        insightsSubtitle: 'Discover the History and Global Success Secrets of K-POP',
    },
    ja: {
        badge: 'AIパーソナルカラー診断',
        title: 'あなたに似ているK-POPアイドルは？',
        subtitle: '写真一枚でパーソナルカラー診断とそっくりアイドルを見つけよう',
        uploadIcon: '📸',
        uploadText: '<span>写真をアップロード</span>またはここにドラッグ＆ドロップ',
        uploadHint: 'JPG, PNG（最大10MB）',
        male: '👨 男性アイドル',
        female: '👩 女性アイドル',
        analyzeBtn: '✨ AI分析を開始する',
        loadingText: 'AIが顔を分析しています...',
        resultTitle: 'パーソナルカラー診断結果',
        resultSubtitle: 'AIが分析したあなたのスタイルレポート',
        bestColors: 'ベストカラー',
        avoidColors: '避けるべきカラー',
        idolTitle: 'そっくりK-POPアイドル TOP 3',
        featureFace: '顔の形',
        featureEye: '目の形',
        featureNose: '鼻の形',
        featureLip: '唇の形',
        featureVibe: '全体の雰囲気',
        ctaBtnText: 'このアイドルのようになりたい？',
        ctaBtnSub: 'AI美容相談所で目鼻の相談を受ける →',
        shareTwitter: '𝕏 Xでシェア',
        saveImage: '📷 結果を保存',
        copyLink: '🔗 リンクをコピー',
        copied: '✅ コピーしました！',
        tweetText: '私に似ているK-POPアイドルは{idol}！あなたのパーソナルカラーとそっくりアイドルを確認してみて ✨ #KPOP #アイドルそっくり #パーソナルカラー https://kpop-idol-ai.vercel.app/',
        linkCopied: '✅ リンクをコピーしました！',
        columnTitle: 'K-Beautyスタイリングガイド',
        footerText: '© 2026 K-POP Idol AI. All rights reserved.',
        errorMsg: '分析中にエラーが発生しました。もう一度お試しください。',
        noImage: '先に写真をアップロードしてください。',
        retryBtn: 'もう一度分析する',
        optimizingText: '🔄 画像を最適化しています...',
        insightsTitle: '🎤 K-POP Insights',
        insightsSubtitle: 'K-POPの歴史とグローバル成功の秘訣を知ろう',
    }
};

export const IDOL_LISTS = {
    male: `[1st Gen] H.O.T, Shinhwa, Sechs Kies, g.o.d, Fly to the Sky, NRG, CLICK-B, 1TYM
[2nd Gen] TVXQ, Super Junior, BIGBANG, SHINee, 2PM, 2AM, SS501, FT Island, CNBLUE, BEAST/Highlight, INFINITE, MBLAQ, ZE:A, TEEN TOP, B1A4, BTOB, U-KISS, MYNAME, B.A.P
[3rd Gen] EXO, BTS, GOT7, SEVENTEEN, MONSTA X, VIXX, iKON, WINNER, DAY6, N.Flying, PENTAGON, SF9, ASTRO, KNK, ONEUS, ONEWE, NU'EST, UP10TION, VICTON, VAV, VERIVERY, A.C.E, THE ROSE
[4th Gen] Stray Kids, ATEEZ, TXT, ENHYPEN, TREASURE, THE BOYZ, AB6IX, CIX, CRAVITY, MCND, DRIPPIN, E'LAST, GHOST9, EPEX, OMEGA X, TEMPEST, TNX, YOUNITE, JUST B, WEi, MIRAE, DKZ, KINGDOM, LUMINOUS, 8TURN, XIKERS, RIIZE, ZEROBASEONE, BOYNEXTDOOR, TWS, NOWADAYS, P1Harmony, &TEAM, NEXZ, VANNER, n.SSign
[5th Gen] SAY MY NAME, CLOSE YOUR EYES, ALD1, AMPERS&ONE, NCT WISH, NCT NEW TEAM, DXMON, EVNNE, PLAVE, LUN8, and ALL newly debuted/pre-debut male groups in 2025-2026`,
    female: `[1st Gen] S.E.S, Fin.K.L, Baby V.O.X, Diva, Jewelry, Sugar
[2nd Gen] Girls' Generation/SNSD, Wonder Girls, KARA, 2NE1, f(x), T-ara, 4Minute, miss A, SISTAR, Brown Eyed Girls, Secret, After School, Rainbow, Nine Muses, Dal Shabet, Davichi, EXID, Hello Venus, BESTie, Girl's Day, AOA, Crayon Pop, STELLAR, FIESTAR, Spica
[3rd Gen] TWICE, BLACKPINK, Red Velvet, MAMAMOO, GFriend/VIVIZ, Oh My Girl, Lovelyz, CLC, DIA, Dreamcatcher, WJSN, MOMOLAND, fromis_9, (G)I-DLE, LOONA, Pristin, gugudan, LABOUM, April, ELRIS, Weki Meki, Cherry Bullet, Rocket Punch, 3YE, BVNDIT, NATURE, EVERGLOW, ITZY, cignature, SECRET NUMBER, Purple Kiss, PIXY, LIGHTSUM, HOT ISSUE, TRI.BE, Billlie, Kep1er
[4th Gen] aespa, IVE, NewJeans, LE SSERAFIM, NMIXX, STAYC, KISS OF LIFE, ILLIT, BABYMONSTER, tripleS, H1-KEY, Lapillus, FIFTY FIFTY, Girls On Top (GOT), CLASS:y, LIMELIGHT, RESCENE, UNIS, BADVILLAIN, YOUNG POSSE
[5th Gen] IZNA, MEOVV, IRISE, AHOF, SAY MY NAME, CLOSE YOUR EYES, AND ALL newly debuted/pre-debut girl groups in 2025-2026`
};
